/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
static yyconst short int yy_accept[653] =
    {   0,
        0,    0,    0,    0,  114,  112,  109,  108,  112,  112,
      112,  112,  106,    4,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,    2,  112,  109,  112,  112,  106,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      109,  108,    0,  107,    0,    0,  106,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   87,    0,    0,    3,    0,    2,    2,    0,  109,
        0,  106,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    2,    0,    0,  111,    0,  111,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   72,    0,    0,    0,
       67,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   65,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  110,
        0,    0,    0,    0,    0,   17,    0,    0,    0,    0,
        0,   40,    0,    0,    0,    6,    0,    0,   42,    0,

        0,    0,   33,    0,    0,    0,   36,   32,    0,    0,
        0,   16,    0,    0,  105,    0,    0,    0,    0,    0,
        0,    0,    0,   93,    0,    0,    0,    0,    0,    0,
       88,   91,   51,    0,    0,    0,    0,    0,    0,   60,
        0,    0,    0,    0,    0,    0,   94,    0,    0,    0,
        0,    0,    0,   55,    0,    0,    0,   45,    0,    0,
        0,    0,    0,    0,    0,    0,   90,    0,    0,    0,
       53,   12,    0,    0,    0,    0,    0,   32,    0,    0,
       25,    0,    0,    0,    0,    0,    0,   10,    0,    0,
        0,    0,    8,    0,    0,    0,    7,    0,    0,    0,

        0,    0,    0,   27,    0,    0,    0,   59,   86,    0,
        0,   80,    0,    0,    0,    0,   74,    0,    0,    0,
        0,    0,   89,    0,    0,    0,    0,  104,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   50,
        0,    0,    0,   58,    0,   64,    0,    0,    0,   52,
        0,    0,   68,    0,    0,    0,   30,   43,    0,    0,
        0,    0,    0,    0,    0,   26,    0,    0,    0,    0,
        0,   13,   28,    0,   21,    0,    0,    0,    0,   79,
        0,   66,   49,   62,   46,    0,    0,   97,    0,   69,
        0,    0,    0,    0,    0,   47,    0,    0,    0,    0,

        0,    0,   48,  101,    0,    0,   56,    0,   54,    0,
        0,   85,    0,    0,    1,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    5,   15,    0,    0,    0,   37,
        0,   20,    0,   95,    0,    0,   92,    0,    0,    0,
       78,    0,    0,    0,    0,   57,   73,   71,    0,    0,
        0,   84,    0,    0,    0,   20,    0,   39,    0,    0,
       31,   11,    9,   19,    0,    0,    0,    0,    0,    0,
        0,  102,    0,    0,    0,    0,    0,    0,    0,    0,
       83,    0,    0,   77,    0,   96,   70,   14,    0,   41,
        0,    0,    0,    0,    0,    0,    0,   75,   98,   61,

        0,  100,   44,   81,   82,    0,    0,    0,   18,    0,
        0,    0,    0,    0,    0,    0,   63,    0,   99,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   34,
       35,    0,    0,    0,    0,    0,   76,  103,    0,    0,
        0,   24,    0,    0,    0,   22,    0,    0,   23,   29,
       38,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    8,    1,    9,    1,
        1,    1,   10,    1,   11,   12,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    1,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
        1,   31,   32,   33,   34,   35,   36,    1,   37,   38,
       39,   40,   41,    1,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,    1,   59,   60,   61,   62,   63,   64,    1,
        1,    1,   12,   12,   12,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    2,    3,    2,    2,    1,    2,    1,    1,    2,
        2,    2,    2,    1,    2,    2,    2,    1,    1,    2,
        1,    2,    2,    1,    2,    2,    1,    2,    1,    2,
        1,    2,    2,    1,    1,    2,    2,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[658] =
    {   0,
        0,   58,   83,   62,  831,  832,   65,  832,  827,  823,
      788,  814,  813,  832,  799,  793,   44,   43,  795,   42,
       62,  794,   60,   63,   68,  805,  791,   95,   84,  102,
      804,   71,   68,   72,   88,   68,   93,   61,   94,   96,
       98,   97,  102,  105,  105,  114,  104,  109,  771,  814,
      143,  832,  813,  171,  166,  175,  178,  181,  190,  193,
      787,  176,  181,  189,  184,  190,  194,  207,  210,  237,
       75,  832,  808,  832,  804,  803,  798,  777,  794,  793,
      158,  778,  791,  784,  789,  769,  773,  775,  777,  781,
      763,  759,  764,  767,  767,  173,  769,  202,  764,  770,

      761,  761,  773,  771,  760,  770,  758,  230,  238,  163,
      739,  728,  738,  733,  718,  721,  718,  720,  732,  717,
      202,  714,  708,  711,  710,  720,  714,  713,  202,  706,
      701,  218,  703,  718,  223,  703,  705,  698,  229,  707,
      711,  714,  713,  699,  705,  697,  230,  690,  693,  688,
      238,  832,  689,  745,  832,  238,  832,  832,  744,  289,
      208,  280,  274,  283,  169,  284,  292,  279,  295,  297,
      301,  305,  832,  743,    0,  832,  736,  735,  728,  714,
      713,  707,  708,  707,  701,  705,  714,  706,  706,  714,
      698,  712,  710,  709,  695,  694,  706,  709,  681,  703,

      695,  687,  701,  695,  690,  691,  692,  683,  694,  682,
      685,  259,  661,  666,  651,  660,  653,  645,  643,  650,
      646,  640,  643,  639,  644,  636,  636,  639,  633,  632,
      633,  631,  636,  641,  642,  626,  832,  625,  635,  625,
      832,  630,  635,  624,  636,  626,  618,  616,  622,  618,
      619,  288,  612,  625,  624,  614,  624,  623,  621,  616,
      620,  605,  612,  601,  832,  614,  598,  608,  607,  596,
      325,  317,  314,  629,  316,  318,  319,  327,  331,  832,
      624,  637,  636,  637,  628,  832,  634,  634,  616,  614,
      627,  832,  603,  625,  617,  606,  626,  607,  832,  609,

      334,  621,  832,  622,  607,  606,  832,  832,  603,  604,
      602,  832,  608,  349,  832,  574,  570,  569,  580,  579,
      565,  567,  576,  832,  575,  561,  573,  568,  575,  570,
      832,  832,  832,  573,  568,  567,  602,  564,  560,  832,
      563,  562,  561,  564,  550,  553,  832,  543,  544,  551,
      544,  557,  542,  832,  548,  543,  551,  832,  548,  547,
      536,  531,  530,  529,  533,  538,  832,  528,  532,  524,
      832,  832,  581,  336,  344,  568,  333,  341,  347,  357,
      832,  560,  562,  557,  561,  547,  542,  832,  561,  542,
      547,  542,  832,  557,  550,  551,  832,  546,  553,  534,

      540,  538,  536,  832,  534,  533,  541,  832,  832,  513,
      501,  832,  511,  502,  500,  496,  832,  508,  504,  501,
      505,  487,  832,  503,  318,  494,  493,  832,  497,  499,
      483,  483,  495,  494,  497,  490,  479,  479,  493,  832,
      488,  473,  485,  832,  477,  832,  469,  470,  482,  832,
      468,  473,  832,  352,  496,  362,  832,  832,  497,  495,
      500,  499,  498,  489,  504,  832,  492,  498,  485,  494,
      482,  832,  832,  471,  832,  485,  480,  473,  466,  832,
      462,  832,  832,  832,  832,  451,  450,  832,  458,  832,
      457,  452,  445,  454,  449,  832,  437,  437,  452,  437,

      441,  438,  832,  832,  439,  434,  832,  429,  832,  435,
      438,  832,  441,  440,  832,  363,  467,  454,  466,  455,
      454,  444,  450,  454,  832,  832,  457,  445,  366,  832,
      443,  832,  421,  832,  427,  426,  832,  424,  422,  413,
      832,  412,  409,  420,  405,  832,  832,  832,  414,  407,
      409,  832,  413,  415,  414,  365,  428,  832,  437,  436,
      832,  832,  832,  832,  441,  419,  425,  424,  436,  425,
      408,  832,  403,  402,  386,  396,  386,  388,  396,  383,
      832,  392,  381,  832,  389,  832,  832,  832,  419,  832,
      421,  421,  404,  406,  409,  417,  400,  832,  832,  832,

      369,  832,  832,  832,  832,  373,  367,  366,  832,  400,
      399,  393,  391,  403,  404,  401,  832,  372,  832,  371,
      398,  390,  392,  381,  396,  380,  377,  351,  343,  832,
      832,  370,  349,  326,  288,  287,  832,  832,  275,  264,
      250,  832,  226,  203,  188,  832,  138,   69,  832,  832,
      832,  832,  400,  403,  405,  407,  410
    } ;

static yyconst short int yy_def[658] =
    {   0,
      652,    1,    1,    3,  652,  652,  652,  652,  652,  653,
      654,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  655,
      652,  652,  652,  656,  656,  656,  656,  656,  656,  656,
      652,   60,   60,   60,   60,   60,   60,   60,   60,  655,
      652,  652,  653,  652,  652,  657,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  655,  652,  652,  652,  652,  652,   60,
       60,   60,   60,   60,  652,   60,   60,   60,   60,   60,
       60,   60,  652,  655,   70,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,   60,   60,  652,   60,   60,   60,   60,   60,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,   60,   60,  652,   60,   60,   60,   60,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,   60,  652,   60,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,   60,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,   60,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,    0,  652,  652,  652,  652,  652
    } ;

static yyconst short int yy_nxt[897] =
    {   0,
        6,    7,    8,    9,    7,   10,    6,    6,   11,   12,
       12,    6,   13,   14,   15,   16,   17,   18,   19,   20,
       21,    6,   22,    6,    6,   23,   24,   25,   26,   27,
       28,   29,   30,    6,    6,   31,    6,    6,   32,    6,
        6,    6,   33,   34,   35,   36,   37,   38,    6,   39,
        6,    6,    6,   40,   41,   42,   43,   44,   45,   46,
       47,   48,    6,   49,   50,   80,   71,   85,   70,   71,
       86,   82,   81,   83,   90,  108,   71,   92,   91,   71,
       87,   93,   95,  109,   51,   52,   53,   54,   51,   55,
       88,   94,   56,   56,   55,   57,   96,   58,   59,   60,

      651,   61,   62,  127,   55,   63,  102,   55,   64,   99,
       65,  128,   66,  100,   67,   68,  103,  104,   69,   55,
      105,  110,   55,  101,  123,  114,  111,  112,  115,  124,
      116,  113,  106,  117,  118,  125,  129,  119,  131,  135,
      136,  120,  132,  138,  121,  140,  133,  144,  126,  122,
      130,  142,  134,  139,  137,  145,  146,  156,  143,  141,
      149,   93,  150,  147,  151,  650,  152,  652,  158,  159,
      148,   94,   71,  158,  159,  160,  652,  158,  159,  652,
      158,  159,  652,  158,  159,  182,  274,  162,  183,  186,
      162,  652,  158,  159,  652,  158,  159,  161,  169,  198,

      199,  166,  161,  168,   86,  161,  163,   91,  167,  652,
      161,  161,   96,  213,  164,  161,  170,  652,   98,  649,
       79,   81,  652,  214,  172,  105,  171,  104,  161,  161,
      201,  161,  202,  648,  108,  652,  652,  106,  652,  173,
      174,  175,  109,  175,  225,  212,  175,  175,  175,  175,
      109,  175,  175,  175,  647,  234,  175,  226,  175,  175,
      235,  175,  175,  314,  175,  238,  175,  271,  175,  175,
      243,  249,  175,  175,  250,  194,  175,  244,  239,  245,
      240,  646,  267,  251,  252,  268,  262,  253,  263,  254,
       71,  269,  162,  160,  645,  161,  192,  273,  275,  315,

      161,  161,  652,  644,  161,  161,  272,  652,  652,  643,
      161,  652,  652,  161,  276,  278,  161,  652,  161,  642,
      652,  197,  161,  652,  277,  652,  161,  372,  373,  652,
      279,  374,  353,  652,  354,  161,  289,  161,  161,  161,
      161,  375,  652,  378,  652,  652,  652,  652,  161,  379,
      377,  398,  161,  314,  161,  652,  380,  161,  641,  652,
      454,  652,  161,  399,  652,  161,  381,  640,  161,  652,
      458,  491,  652,  161,  391,  652,  492,  404,  161,  456,
      652,  516,  567,  161,  161,  652,  161,  639,  638,  315,
      652,  652,  568,  652,  569,  570,  637,  636,  635,  556,

       73,   73,   73,   75,   75,  154,  154,  154,  161,  161,
      177,  177,  634,  633,  632,  631,  630,  629,  628,  627,
      626,  625,  624,  623,  622,  621,  620,  619,  618,  617,
      616,  615,  614,  613,  612,  611,  610,  609,  608,  607,
      606,  605,  604,  603,  602,  601,  600,  599,  598,  597,
      596,  595,  594,  593,  592,  591,  590,  589,  588,  587,
      586,  585,  584,  583,  582,  581,  580,  579,  578,  577,
      576,  575,  574,  573,  572,  571,  566,  565,  564,  563,
      562,  561,  560,  559,  558,  557,  555,  554,  553,  552,
      551,  550,  549,  548,  547,  546,  545,  544,  543,  542,

      541,  540,  539,  538,  537,  536,  535,  534,  533,  532,
      531,  530,  529,  528,  527,  526,  525,  524,  523,  522,
      521,  520,  519,  518,  517,  515,  514,  513,  512,  511,
      510,  509,  508,  507,  506,  505,  504,  503,  502,  501,
      500,  499,  498,  497,  496,  495,  494,  493,  490,  489,
      488,  487,  486,  485,  484,  483,  482,  481,  480,  479,
      478,  477,  476,  475,  474,  473,  472,  471,  470,  469,
      468,  467,  466,  465,  464,  463,  462,  461,  460,  459,
      458,  457,  455,  372,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,

      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  376,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,

      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  280,  173,  158,  155,  270,  266,
      265,  264,  261,  260,  259,  258,  257,  256,  255,  248,
      247,  246,  242,  241,  237,  236,  233,  232,  231,  230,
      229,  228,  227,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  200,  197,  196,  195,  194,  193,  192,  191,

      190,  189,  188,  187,  186,  185,  184,  181,  180,  179,
       77,  178,  176,   74,  165,  157,  155,  153,  107,   98,
       97,   89,   84,   79,   78,   77,   77,   76,   74,   72,
      652,    5,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652

    } ;

static yyconst short int yy_chk[897] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,   17,    7,   20,    4,    7,
       20,   18,   17,   18,   23,   32,   71,   24,   23,   71,
       21,   24,   25,   32,    2,    3,    3,    3,    4,    3,
       21,   24,    3,    3,    3,    3,   25,    3,    3,    3,

      648,    3,    3,   38,    3,    3,   29,    3,    3,   28,
        3,   38,    3,   28,    3,    3,   29,   29,    3,    3,
       30,   33,    3,   28,   36,   34,   33,   33,   34,   36,
       34,   33,   30,   34,   35,   37,   39,   35,   40,   41,
       41,   35,   40,   42,   35,   43,   40,   45,   37,   35,
       39,   44,   40,   42,   41,   45,   46,   51,   44,   43,
       47,   51,   47,   46,   48,  647,   48,   55,   55,   55,
       46,   51,   54,   54,   54,   54,   56,   56,   56,   57,
       57,   57,   58,   58,   58,   81,  165,   56,   81,  165,
       57,   59,   59,   59,   60,   60,   60,   62,   65,   96,

       96,   62,   63,   64,   62,   65,   58,   64,   63,   63,
       64,   66,   65,  110,   60,   67,   67,   64,   66,  645,
       59,   60,   67,  110,   69,   68,   67,   67,   68,  161,
       98,   69,   98,  644,  108,   68,  161,   68,   69,   70,
       70,   70,  108,   70,  121,  109,   70,   70,   70,   70,
      109,   70,   70,   70,  643,  129,   70,  121,   70,   70,
      129,   70,   70,  212,   70,  132,   70,  156,   70,   70,
      135,  139,   70,   70,  139,  156,   70,  135,  132,  135,
      132,  641,  151,  139,  139,  151,  147,  139,  147,  139,
      160,  151,  162,  160,  640,  163,  168,  164,  166,  212,

      168,  162,  163,  639,  164,  166,  163,  168,  162,  636,
      160,  164,  166,  167,  167,  171,  169,  160,  170,  635,
      167,  169,  171,  169,  170,  170,  172,  271,  271,  171,
      172,  272,  252,  172,  252,  273,  275,  275,  272,  276,
      277,  273,  273,  277,  275,  272,  276,  277,  278,  278,
      276,  301,  279,  314,  377,  278,  279,  374,  634,  279,
      375,  377,  378,  301,  374,  375,  374,  633,  379,  378,
      454,  425,  375,  454,  377,  379,  425,  379,  380,  380,
      454,  456,  529,  456,  516,  380,  556,  632,  629,  314,
      456,  516,  529,  556,  529,  529,  628,  627,  626,  516,

      653,  653,  653,  654,  654,  655,  655,  655,  656,  656,
      657,  657,  625,  624,  623,  622,  621,  620,  618,  616,
      615,  614,  613,  612,  611,  610,  608,  607,  606,  601,
      597,  596,  595,  594,  593,  592,  591,  589,  585,  583,
      582,  580,  579,  578,  577,  576,  575,  574,  573,  571,
      570,  569,  568,  567,  566,  565,  560,  559,  557,  555,
      554,  553,  551,  550,  549,  545,  544,  543,  542,  540,
      539,  538,  536,  535,  533,  531,  528,  527,  524,  523,
      522,  521,  520,  519,  518,  517,  514,  513,  511,  510,
      508,  506,  505,  502,  501,  500,  499,  498,  497,  495,

      494,  493,  492,  491,  489,  487,  486,  481,  479,  478,
      477,  476,  474,  471,  470,  469,  468,  467,  465,  464,
      463,  462,  461,  460,  459,  455,  452,  451,  449,  448,
      447,  445,  443,  442,  441,  439,  438,  437,  436,  435,
      434,  433,  432,  431,  430,  429,  427,  426,  424,  422,
      421,  420,  419,  418,  416,  415,  414,  413,  411,  410,
      407,  406,  405,  403,  402,  401,  400,  399,  398,  396,
      395,  394,  392,  391,  390,  389,  387,  386,  385,  384,
      383,  382,  376,  373,  370,  369,  368,  366,  365,  364,
      363,  362,  361,  360,  359,  357,  356,  355,  353,  352,

      351,  350,  349,  348,  346,  345,  344,  343,  342,  341,
      339,  338,  337,  336,  335,  334,  330,  329,  328,  327,
      326,  325,  323,  322,  321,  320,  319,  318,  317,  316,
      313,  311,  310,  309,  306,  305,  304,  302,  300,  298,
      297,  296,  295,  294,  293,  291,  290,  289,  288,  287,
      285,  284,  283,  282,  281,  274,  270,  269,  268,  267,
      266,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  240,  239,  238,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,

      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  174,  159,  154,  153,  150,
      149,  148,  146,  145,  144,  143,  142,  141,  140,  138,
      137,  136,  134,  133,  131,  130,  128,  127,  126,  125,
      124,  123,  122,  120,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  107,  106,  105,  104,  103,  102,  101,
      100,   99,   97,   95,   94,   93,   92,   91,   90,   89,

       88,   87,   86,   85,   84,   83,   82,   80,   79,   78,
       77,   76,   75,   73,   61,   53,   50,   49,   31,   27,
       26,   22,   19,   16,   15,   13,   12,   11,   10,    9,
        5,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lev_comp.l"
#define INITIAL 0
#line 2 "lev_comp.l"
/*	SCCS Id: @(#)lev_lex.c	3.4	2002/03/27	*/
/*	Copyright (c) 1989 by Jean-Christophe Collet */
/* NetHack may be freely redistributed.  See license for details. */

#define LEV_LEX_C

#include "hack.h"
#include "lev_comp.h"
#include "sp_lev.h"

/* Most of these don't exist in flex, yywrap is macro and
 * yyunput is properly declared in flex.skel.
 */
#if !defined(FLEX_SCANNER) && !defined(FLEXHACK_SCANNER)
int FDECL(yyback, (int *,int));
int NDECL(yylook);
int NDECL(yyinput);
int NDECL(yywrap);
int NDECL(yylex);
	/* Traditional lexes let yyunput() and yyoutput() default to int;
	 * newer ones may declare them as void since they don't return
	 * values.  For even more fun, the lex supplied as part of the
	 * newer unbundled compiler for SunOS 4.x adds the void declarations
	 * (under __STDC__ or _cplusplus ifdefs -- otherwise they remain
	 * int) while the bundled lex and the one with the older unbundled
	 * compiler do not.  To detect this, we need help from outside --
	 * sys/unix/Makefile.utl.
	 *
	 * Digital UNIX is difficult and still has int in spite of all
	 * other signs.
	 */
# if defined(NeXT) || defined(SVR4) || defined(_AIX32)
#  define VOIDYYPUT
# endif
# if !defined(VOIDYYPUT) && defined(POSIX_TYPES)
#  if !defined(BOS) && !defined(HISX) && !defined(_M_UNIX) && !defined(VMS)
#   define VOIDYYPUT
#  endif
# endif
# if !defined(VOIDYYPUT) && defined(WEIRD_LEX)
#  if defined(SUNOS4) && defined(__STDC__) && (WEIRD_LEX > 1)
#   define VOIDYYPUT
#  endif
# endif
# if defined(VOIDYYPUT) && defined(__osf__)
#  undef VOIDYYPUT
# endif
# ifdef VOIDYYPUT
void FDECL(yyunput, (int));
void FDECL(yyoutput, (int));
# else
int FDECL(yyunput, (int));
int FDECL(yyoutput, (int));
# endif
#endif	/* !FLEX_SCANNER && !FLEXHACK_SCANNER */

#ifdef FLEX_SCANNER
#define YY_MALLOC_DECL \
	      genericptr_t FDECL(malloc, (size_t)); \
	      genericptr_t FDECL(realloc, (genericptr_t,size_t));
#endif

void FDECL(init_yyin, (FILE *));
void FDECL(init_yyout, (FILE *));

/*
 * This doesn't always get put in lev_comp.h
 * (esp. when using older versions of bison).
 */
extern YYSTYPE yylval;

int line_number = 1, colon_line_number = 1;
static char map[4096];
static int map_cnt = 0;

#define MAPC 1

#line 856 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 82 "lev_comp.l"

#line 1012 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 653 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 832 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 83 "lev_comp.l"
{
		  BEGIN(INITIAL);
		  yylval.map = (char *) alloc(map_cnt + 1);
		  (void) strncpy(yylval.map, map, map_cnt);
		  yylval.map[map_cnt] = 0;
		  map_cnt = 0;
		  return MAP_ID;
		}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 91 "lev_comp.l"
{
		  int len = yyleng;
		  /* convert \r\n to \n */
		  if (len >= 2 && yytext[len - 2] == '\r') len -= 1;
		  line_number++;
		  (void) strncpy(map + map_cnt, yytext, len);
		  map_cnt += len;
		  map[map_cnt - 1] = '\n';
		  map[map_cnt] = '\0';
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 101 "lev_comp.l"
{ line_number++; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 102 "lev_comp.l"
{ colon_line_number = line_number; return ':'; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 103 "lev_comp.l"
return MESSAGE_ID;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 104 "lev_comp.l"
return MAZE_ID;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 105 "lev_comp.l"
return NOMAP_ID;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 106 "lev_comp.l"
return LEVEL_ID;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 107 "lev_comp.l"
return LEV_INIT_ID;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 108 "lev_comp.l"
return FLAGS_ID;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 109 "lev_comp.l"
return GEOMETRY_ID;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "lev_comp.l"
{ BEGIN(MAPC); line_number++; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 111 "lev_comp.l"
return OBJECT_ID;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 112 "lev_comp.l"
return COBJECT_ID;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 113 "lev_comp.l"
return MONSTER_ID;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 114 "lev_comp.l"
return TRAP_ID;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 115 "lev_comp.l"
return DOOR_ID;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 116 "lev_comp.l"
return DRAWBRIDGE_ID;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 117 "lev_comp.l"
return MAZEWALK_ID;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 118 "lev_comp.l"
return WALLIFY_ID;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 119 "lev_comp.l"
return REGION_ID;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 120 "lev_comp.l"
return RANDOM_OBJECTS_ID;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 121 "lev_comp.l"
return RANDOM_MONSTERS_ID;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 122 "lev_comp.l"
return RANDOM_PLACES_ID;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 123 "lev_comp.l"
return ALTAR_ID;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 124 "lev_comp.l"
return LADDER_ID;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 125 "lev_comp.l"
return STAIR_ID;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 126 "lev_comp.l"
return PORTAL_ID;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 127 "lev_comp.l"
return TELEPRT_ID;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 128 "lev_comp.l"
return BRANCH_ID;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 129 "lev_comp.l"
return FOUNTAIN_ID;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 130 "lev_comp.l"
return SINK_ID;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 131 "lev_comp.l"
return POOL_ID;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 132 "lev_comp.l"
return NON_DIGGABLE_ID;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 133 "lev_comp.l"
return NON_PASSWALL_ID;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 134 "lev_comp.l"
return ROOM_ID;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 135 "lev_comp.l"
return SUBROOM_ID;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 136 "lev_comp.l"
return RAND_CORRIDOR_ID;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 137 "lev_comp.l"
return CORRIDOR_ID;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 138 "lev_comp.l"
return GOLD_ID;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 139 "lev_comp.l"
return ENGRAVING_ID;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 140 "lev_comp.l"
return NAME_ID;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 141 "lev_comp.l"
return CHANCE_ID;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 142 "lev_comp.l"
return LEV;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 143 "lev_comp.l"
{ yylval.i=D_ISOPEN; return DOOR_STATE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 144 "lev_comp.l"
{ yylval.i=D_CLOSED; return DOOR_STATE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 145 "lev_comp.l"
{ yylval.i=D_LOCKED; return DOOR_STATE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 146 "lev_comp.l"
{ yylval.i=D_NODOOR; return DOOR_STATE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 147 "lev_comp.l"
{ yylval.i=D_BROKEN; return DOOR_STATE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 148 "lev_comp.l"
{ yylval.i=W_NORTH; return DIRECTION; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 149 "lev_comp.l"
{ yylval.i=W_EAST; return DIRECTION; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 150 "lev_comp.l"
{ yylval.i=W_SOUTH; return DIRECTION; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 151 "lev_comp.l"
{ yylval.i=W_WEST; return DIRECTION; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 152 "lev_comp.l"
{ yylval.i = -1; return RANDOM_TYPE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 153 "lev_comp.l"
{ yylval.i = -2; return NONE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 154 "lev_comp.l"
return O_REGISTER;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 155 "lev_comp.l"
return M_REGISTER;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 156 "lev_comp.l"
return P_REGISTER;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 157 "lev_comp.l"
return A_REGISTER;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 158 "lev_comp.l"
{ yylval.i=1; return LEFT_OR_RIGHT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 159 "lev_comp.l"
{ yylval.i=2; return LEFT_OR_RIGHT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 160 "lev_comp.l"
{ yylval.i=3; return CENTER; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 161 "lev_comp.l"
{ yylval.i=4; return LEFT_OR_RIGHT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 162 "lev_comp.l"
{ yylval.i=5; return LEFT_OR_RIGHT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 163 "lev_comp.l"
{ yylval.i=1; return TOP_OR_BOT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 164 "lev_comp.l"
{ yylval.i=5; return TOP_OR_BOT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 165 "lev_comp.l"
{ yylval.i=1; return LIGHT_STATE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 166 "lev_comp.l"
{ yylval.i=0; return LIGHT_STATE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 167 "lev_comp.l"
{ yylval.i=0; return FILLING; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 168 "lev_comp.l"
{ yylval.i=1; return FILLING; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 169 "lev_comp.l"
{ yylval.i= AM_NONE; return ALIGNMENT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 170 "lev_comp.l"
{ yylval.i= AM_LAWFUL; return ALIGNMENT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 171 "lev_comp.l"
{ yylval.i= AM_NEUTRAL; return ALIGNMENT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 172 "lev_comp.l"
{ yylval.i= AM_CHAOTIC; return ALIGNMENT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 173 "lev_comp.l"
{ yylval.i= AM_SPLEV_CO; return ALIGNMENT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 174 "lev_comp.l"
{ yylval.i= AM_SPLEV_NONCO; return ALIGNMENT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 175 "lev_comp.l"
{ yylval.i=1; return MON_ATTITUDE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 176 "lev_comp.l"
{ yylval.i=0; return MON_ATTITUDE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 177 "lev_comp.l"
{ yylval.i=1; return MON_ALERTNESS; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 178 "lev_comp.l"
{ yylval.i=0; return MON_ALERTNESS; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 179 "lev_comp.l"
{ yylval.i= M_AP_FURNITURE; return MON_APPEARANCE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 180 "lev_comp.l"
{ yylval.i= M_AP_MONSTER;   return MON_APPEARANCE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 181 "lev_comp.l"
{ yylval.i= M_AP_OBJECT;    return MON_APPEARANCE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 182 "lev_comp.l"
{ yylval.i=2; return ALTAR_TYPE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 183 "lev_comp.l"
{ yylval.i=1; return ALTAR_TYPE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 184 "lev_comp.l"
{ yylval.i=0; return ALTAR_TYPE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 185 "lev_comp.l"
{ yylval.i=1; return UP_OR_DOWN; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 186 "lev_comp.l"
{ yylval.i=0; return UP_OR_DOWN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 187 "lev_comp.l"
{ yylval.i=0; return BOOLEAN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 188 "lev_comp.l"
{ yylval.i=1; return BOOLEAN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 189 "lev_comp.l"
{ yylval.i=DUST; return ENGRAVING_TYPE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 190 "lev_comp.l"
{ yylval.i=ENGRAVE; return ENGRAVING_TYPE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 191 "lev_comp.l"
{ yylval.i=BURN; return ENGRAVING_TYPE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 192 "lev_comp.l"
{ yylval.i=MARK; return ENGRAVING_TYPE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 193 "lev_comp.l"
{ yylval.i=1; return CURSE_TYPE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 194 "lev_comp.l"
{ yylval.i=2; return CURSE_TYPE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 195 "lev_comp.l"
{ yylval.i=3; return CURSE_TYPE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 196 "lev_comp.l"
{ return CONTAINED; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 197 "lev_comp.l"
{ yylval.i=NOTELEPORT; return FLAG_TYPE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 198 "lev_comp.l"
{ yylval.i=HARDFLOOR; return FLAG_TYPE; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 199 "lev_comp.l"
{ yylval.i=NOMMAP; return FLAG_TYPE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 200 "lev_comp.l"
{ yylval.i=ARBOREAL; return FLAG_TYPE; }	/* KMH */
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 201 "lev_comp.l"
{ yylval.i=SHORTSIGHTED; return FLAG_TYPE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 202 "lev_comp.l"
{ yylval.i=LETHE; return FLAG_TYPE; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 203 "lev_comp.l"
{ yylval.i = atoi(yytext + 1); return PERCENT; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 204 "lev_comp.l"
{ yylval.i=atoi(yytext); return INTEGER; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 205 "lev_comp.l"
{ yytext[yyleng-1] = 0; /* Discard the trailing \" */
		  yylval.map = (char *) alloc(strlen(yytext+1)+1);
		  Strcpy(yylval.map, yytext+1); /* Discard the first \" */
		  return STRING; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 209 "lev_comp.l"
{ line_number++; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 210 "lev_comp.l"
;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 211 "lev_comp.l"
{ yylval.i = yytext[2]; return CHAR; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 212 "lev_comp.l"
{ yylval.i = yytext[1]; return CHAR; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 213 "lev_comp.l"
{ return yytext[0]; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 214 "lev_comp.l"
ECHO;
	YY_BREAK
#line 1680 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MAPC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 653 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 653 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 652);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 214 "lev_comp.l"

#ifdef	AMIGA
long *alloc(n)
	unsigned n;
{
	return ((long *)malloc (n));
}
#endif

/* routine to switch to another input file; needed for flex */
void init_yyin( input_f )
FILE *input_f;
{
#if defined(FLEX_SCANNER) || defined(FLEXHACK_SCANNER)
	if (yyin)
	    yyrestart(input_f);
	else
#endif
	    yyin = input_f;
}
/* analogous routine (for completeness) */
void init_yyout( output_f )
FILE *output_f;
{
	yyout = output_f;
}

/*lev_comp.l, yo*/
